### ISSUE TITLE
上傳週報的日期只需要選擇年月日，不加時間

### ISSUE THREAD

**Issue by jennifershih** [CatenChurch/caten-church#86]
目前發布時間為年月日和時間
建議將時間拿掉，可以方便相關人員操作功能。

**Comment by jk195417** [comment]
那個欄位是 for 未來有個功能做排程，這個時間之後才能看到此週報

**Comment by jennifershih** [comment]
是 例如發布日期選擇2020/03/18，可以判斷3/18 凌晨00:00自動發布週報，不需要選擇到時間。
此外，建議上傳週報的欄位可多添加發布人，可以有個記錄 誰是上傳週報的人員。
